### ISSUE TITLE
Missing getters for `.aborted` and `.complete`

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/mimic-response#5]
These properties may change, e.g. on the `end` event. Because `.complete` is always `false`, even after the `end` event, it's not possible to detect aborted requests via `request.destroyed && !response.complete`.

**Comment by sindresorhus** [comment]
I think if we use `Object.getOwnPropertyDescriptor` and `Object.defineProperty` we can copy the properties and also preserve any getters.

**Comment by szmarczak** [comment]
Actually that won't work because `.complete` is not a getter :|
